ccflags-y += -Idrivers/media/platform/msm/camera_v2_letv/sensor/cci
ccflags-y += -Idrivers/media/platform/msm/camera_v2_letv
ccflags-y += -Idrivers/media/platform/msm/camera_v2_letv/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2_letv/sensor/io
obj-$(CONFIG_MSM_I2C_FLASH) += lm3643.o
obj-$(CONFIG_MSMB_CAMERA) += msm_flash.o
