ccflags-y += -Idrivers/media/platform/msm/camera_v2_letv
ccflags-y += -Idrivers/media/platform/msm/camera_v2_letv/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2_letv/msm_vb2
ccflags-y += -Idrivers/media/platform/msm/camera_v2_letv/camera
ccflags-y += -Idrivers/media/platform/msm/camera_v2_letv/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_letv/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += cci/ io/ csiphy/ csid/ actuator/ eeprom/ ois/ flash/
obj-$(CONFIG_MSM_CAMERA_SENSOR) += msm_sensor_init.o msm_sensor_driver.o msm_sensor.o
