ccflags-y += -Idrivers/media/platform/msm/camera_v2_letv
ccflags-y += -Idrivers/media/platform/msm/camera_v2_letv/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2_letv/sensor/io
obj-$(CONFIG_MSM_CCI) += msm_cci.o
