ccflags-y += -Idrivers/media/platform/msm/camera_v2_letv
ccflags-y += -Idrivers/media/platform/msm/camera_v2_letv/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_letv/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_letv/common
obj-$(CONFIG_MSM_CPP) += msm_cpp_soc.o msm_cpp.o
