ccflags-y += -Idrivers/media/platform/msm/camera_v2_letv
ccflags-y += -Idrivers/media/platform/msm/camera_v2_letv/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2_letv/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_letv/sensor/cci
obj-$(CONFIG_MSM_EEPROM) += msm_eeprom_letv.o
